name: Event filters and activity types
run-name: contexts env ${{inputs.target-env}}
env:
 myjob: "Current"
on: 
 pull_request:
 workflow_dispatch:

  inputs:
   target-env:
    type: environment
    default: staging
   
    description: "hey whatsapp"
   
    
   

 
 
  
jobs:
 backwards-compatibility:
  runs-on: ${{ matrix.os}}
  strategy:
   matrix:
    node-version: [18.x,20.x,21.x]
    os: [ubuntu-latest,windows-latest]
    exclude:
      - node-version: 21.x
        os: windows-latest
  outputs:
   build-status: ${{steps.build.outputs.status}}
  steps:
  - name: setup node
    uses: actions/setup-node@v3
    with:
     node-version: ${{matrix.node-version}}
  - name: Perform test
    run: echo "running test on ${{matrix.os}} and in ${{matrix.node-version}}"
     
    
  
 unit-test:
  runs-on: ubuntu-latest
  continue-on-error: true
  steps:
  - name: Running unit tests
    run: echo "Running tests..."
  - name: Failing tests
    if: ${{!inputs.pass-unit-tests}}
    run: exit 1
 
  
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
