name: Event filters and activity types
run-name: contexts ${{inputs.debug && 'ON'||'OFF'}}
env:
 myjob: "Current"
on: 
 pull_request:
 workflow_dispatch:

  inputs:
   debug:
    type: boolean
    default: false
    
   

 
 
  
jobs:
 echo:
  runs-on: ubuntu-latest
  steps:
  - name: Failing step
    run: echo "Hello"
  - name: I will be skipped
    if: ${{success()}}
    run: echo "I will print if previous steps succeed"
  - name: I will be skipped
    if: ${{failure()}}
    run: echo "I will print if previous steps fails"
  - name: I will be skipped
    if: ${{!cancelled()}}
    run: echo "I will print if not cancel"
  - name: I will be skipped
    if: ${{cancelled()}}
    run: echo "I will print if cancel"
  
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
