name: Event filters and activity types
run-name: contexts ${{inputs.string}}
env:
 myjob: "Current"
on: 
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
    
   

 
 
  
jobs:
 ubuntu-echo:
  runs-on: ubuntu-latest
  env:
   myjob: "new"
  steps:
  - name: show the os
    run: | 
      echo "event name is ${{github.event_name}}"
      echo "ref name is ${{github.ref}}"
      echo "sha name is ${{github.sha}}"
      echo "actor name is ${{github.actor}}"
      echo "env name is ${{env.myjob}}"
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
