name: Event filters and activity types

on: 
 pull_request:
 workflow_call:

  inputs:
   target-env:
    type: string
    default: staging
   
    description: "hey whatsapp"
  outputs:
   build-status:
    description: "The status of the build process"
    value: ${{jobs.deploy.outputs.build-status}}
   url:
    description: "The url description"
    value: ${{jobs.deploy.outputs.url}}
jobs:
  deploy:
   runs-on: ubuntu-latest
   outputs:
     build-status: ${{steps.build.outputs.build-status}}
     url: ${{steps.deploy.outputs.url}}
   steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Build
      id: build
      run: |
       echo "Building using directory ${{inputs.target-env}}"
       echo "build-status=Success" >> "$GITHUB_OUTPUT"
    - name: Deploy
      id: deploy
      run: |
       echo "Building using directory ${{inputs.target-env}}"
       echo "url= https://www.google.com" >> "$GITHUB_OUTPUT"
    
   
   
   
   
    
   

 
 
