name: Workflow events
on: 
 workflow_dispatch
 
 
  
jobs:
 ubuntu-echo:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Triggered by ${{RUNNER_OS}}"
      echo "helloo"
     
     
