name: Event filters and activity types
run-name: contexts ${{inputs.debug && 'ON'||'OFF'}}
env:
 myjob: "Current"
on: 
 pull_request:
 workflow_dispatch:

  inputs:
   pass-unit-tests:
    type: boolean
    default: false
    
   

 
 
  
jobs:
 lint-build:
  runs-on: ubuntu-latest
  steps:
  - name: Lint and build
    run: echo "Linting and building project"
 unit-test:
  runs-on: ubuntu-latest
  steps:
  - name: Running unit tests
    run: echo "Running tests..."
  - name: Failing tests
    if: ${{!input.pass-unit-tests}}
    run: exit 1
  -
  
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
