name: Workflow events
on: 
 push:
 pull_request:
 
  
jobs:
 echo:
  runs-on: ubuntu-latest
  steps:
  - name: show the trigger
    run: echo "Triggered by  updated ${{github.event_name}}"
     
     
