name: Event filters and activity types
on: 
 workflow_dispatch:
 pull_request:
  types:
   - opened
   - synchronize
  branches:
   - main
   

 
 
  
jobs:
 ubuntu-echo:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Triggered by opened or synchronize and base branch should be main"
      echo "helloo"

      echo "Triggered by $RUNNER_OS"
      echo "helloo"  
     
