name: Event filters and activity types
run-name: contexts ${{inputs.debug && 'ON'||'OFF'}}
env:
 myjob: "Current"
on: 
 pull_request:
 workflow_dispatch:

  inputs:
   build-status:
    type: choice
    default: Success
    options:
     - Success
     - Failure
    description: "hey whatsapp"
   
    
   

 
 
  
jobs:
 backwards-compatibility:
  runs-on: ${{ matrix.os}}
  strategy:
   matrix:
    node-version: [18.x,20.x,21.x]
    os: [ubuntu-latest,windows-latest]
    
  outputs:
   build-status: ${{steps.build.outputs.status}}
  steps:
  - name: setup node
    uses: actions/setup-node@v3
    with: ${{matrix.node-version}}
  - name: Perform test
    run: running test on ${{matrix.os}} and in ${{matrix.node-version}}
     
    
  - name: build2
    id: build
    run: echo "status=${{inputs.build-status}}">> $GITHUB_OUTPUT
 
 unit-test:
  runs-on: ubuntu-latest
  continue-on-error: true
  steps:
  - name: Running unit tests
    run: echo "Running tests..."
  - name: Failing tests
    if: ${{!inputs.pass-unit-tests}}
    run: exit 1
 
  
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
