name: Event filters and activity types
run-name: contexts ${{inputs.debug && 'ON'||'OFF'}}
env:
 myjob: "Current"
on: 
 pull_request:
 workflow_dispatch:

  inputs:
   build-status:
    type: choice
    default: Success
    options:
     - Success
     - Failure
    description: "hey whatsapp"
   
    
   

 
 
  
jobs:
 build:
  runs-on: ubuntu-latest
  outputs:
   build-status: ${{steps.build.outputs.status}}
  steps:
  - name: print output
    run: echo "Build from $GITHUB_OUTPUT"
  - name: build2
    id: build
    run: echo "status=${{inputs.build-status}}">> $GITHUB_OUTPUT
 deploy:
  runs-on: ubuntu-latest
  needs:
  - build
  if: ${{needs.build.outputs.build-status == 'Success'}}
  steps:
  - name: print output
    run: echo "Build from $GITHUB_OUTPUT"
  - name: build2
    id: build
    run: echo "status=success">> $GITHUB_OUTPUT
 unit-test:
  runs-on: ubuntu-latest
  continue-on-error: true
  steps:
  - name: Running unit tests
    run: echo "Running tests..."
  - name: Failing tests
    if: ${{!inputs.pass-unit-tests}}
    run: exit 1
 
  
 ubuntu-echo2:
  runs-on: ubuntu-latest
  steps:
  - name: show the os
    run: | 
      echo "Retrive value is ${{vars.MY_VAR}}"
     
