name: Reusable Workflow
on:
 workflow_dispatch:
jobs:
 deploy:
  uses: ./.github/workflows/first-action.yaml
  with:
    target-directory: dummy-dir
 print-outputs:
  runs-on: ubuntu-latest
  needs: deploy
  steps:
   - name: Print output
     run: |
       echo "Build status: ${{needs.deploy.outputs.build-status}}"
       echo "url: ${{needs.deploy.outputs.url}}"
       
  

